apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coredns-operator
  labels:
    k8s-app: coredns-operator
rules:
- apiGroups:
  - addons.k8s.io
  resources:
  - coredns
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - addons.k8s.io
  resources:
  - coredns/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - ""
  resources:
  - endpoints
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coredns-operator
  labels:
    k8s-app: coredns-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coredns-operator
subjects:
- kind: ServiceAccount
  name: coredns-operator
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns-operator
  namespace: kube-system
  labels:
    k8s-app: coredns-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: coredns-operator
  name: coredns-operator
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: coredns-operator
  template:
    metadata:
      labels:
        k8s-app: coredns-operator
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        command:
        - /manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: IMAGE_NAME
        imagePullPolicy: Always
        name: manager
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      serviceAccount: coredns-operator
      terminationGracePeriodSeconds: 10
