# permissions for end users to edit ingressnginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressnginx-editor-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - ingressnginxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - ingressnginxes/status
  verbs:
  - get
