apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  annotations:
    config.k8s.io/function: |
      container:
        image: justinsb/kaml-set-annotations
    config.kubernetes.io/local-config: 'true'
data:
  annotations:
    foo: barz
