apiVersion: addons.k8s.io/v1alpha1
kind: CoreDNS
metadata:
  name: default
  namespace: kube-system
spec:
  channel: stable
  patches:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: coredns
      namespace: kube-system
      labels:
        foo: bar
