# permissions for end users to edit ciliumnetworkings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ciliumnetworking-editor-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - ciliumnetworkings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - ciliumnetworkings/status
  verbs:
  - get
