# permissions to do edit clustermanagedapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustermanagedapplication-editor-role
rules:
- apiGroups:
  - app.k8s.io
  resources:
  - clustermanagedapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.k8s.io
  resources:
  - clustermanagedapplications/status
  verbs:
  - get
  - patch
  - update
