# permissions for end users to edit caliconetworkings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caliconetworking-editor-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - caliconetworkings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - caliconetworkings/status
  verbs:
  - get
